<?php

/**
 * @file
 * Implemented hooks and functions of Beam Migrate module.
 */

use Drupal\bean_migrate\MigrationPluginAlterer;

/**
 * Implements hook_migration_plugins_alter().
 */
function bean_migrate_migration_plugins_alter(array &$migrations) {
  // Make every migration plugin definition compatible with Bean Migrate.
  MigrationPluginAlterer::alterFieldInstanceMigrations($migrations);
  MigrationPluginAlterer::fixBlockContentMigrations($migrations);
  MigrationPluginAlterer::copyCoreBlockRegionMappingToBeanBlockPlacement($migrations);
  MigrationPluginAlterer::mapBeanToBlockContent($migrations);
  MigrationPluginAlterer::finalizeDerivedFieldMigrations($migrations);
  MigrationPluginAlterer::removeUuidProcessIfNotNeeded($migrations);
}
